#!/bin/bash
SKETCH_BASE=$1
BASE=/Users/dhopson/Documents/Arduino
SKETCH=$BASE/Sketches/$SKETCH_BASE/${SKETCH_BASE}.ino
BUILD=$BASE/build
BUILDER=$BASE/go
ARDUINO15=/Users/dhopson/Library/Arduino15
TOOLS_BUILDER=/Applications/Arduino.app/Contents/Java/tools-builder
#BASEVER=1

if [ $# -ne 1 ]; then
   echo $0: "usages: sketch"
   exit 1
fi

if [ -f $SKETCH ]; then
   echo "SKETCH = ${SKETCH}"
else
   echo "No sketch provided"
   echo $0: "usages: sketch"
   exit 1
fi	


function build_sketch {
   echo "Compling sketch ${SKETCH_BASE} version ${BASEVER}.${VER}"
   echo " "
   sed -i.bak "s/CHANGENAME/${SKETCH_BASE}.ino/" $SKETCH
   $BUILDER/arduino-builder \
      -compile \
      -hardware $ARDUINO15/packages \
      -hardware $BASE/hardware \
      -tools $ARDUINO15/packages/esp8266/tools \
      -tools $TOOLS_BUILDER \
      -libraries $BASE/libraries \
      -fqbn=esp8266:esp8266:nodemcuv2:CpuFrequency=160,UploadSpeed=115200,FlashSize=4M3M \
      -build-path $BUILD \
      -verbose \
      $SKETCH
   status=$?
   sed -i.bak "s/${SKETCH_BASE}.ino/CHANGENAME" $SKETCH
   echo "build_sketch status = $status"
   echo " "
   echo "Finished Compling sketch ${SKETCH}"
   echo " "
   return $status
}

function uploadSerial {
   echo " "
   echo "uploading $BUILD/${SKETCH_BASE}.ino.bin version ${BASEVER}.${VER} via port /dev/cu/SLAB_USBtoUART"
   echo " "
   if [ -f $BUILD/${SKETCH_BASE}.ino.bin ]; then
        esptool.py --chip esp8266 --port /dev/cu.SLAB_USBtoUART --baud 115200 --after hard_reset write_flash -fm dout 0x00000 $BUILD/${SKETCH_BASE}.ino.bin 
   else
        echo "no sketch firmware to upload"
   fi     
}

# Main function
#get_version
#read -p "Press [Enter] key to continue..."
#sed -i.bak "s/changeme/${SKETCH_BASE}.ino/" $SKETCH

#if [ ${BUMP} != "-u" ]; then
#   build_sketch
#fi   
build_sketch
echo "status = $status"
echo "build finished"
if [ $status == 0 ]; then 
   uploadSerial
fi
